# ID : GO_STP_553



# Assignment/Task 4

Question on Numpy-

1. Import the numpy package under the name np and Print the numpy version and the configuration 

In [1]:
import numpy as np
np.__version__

'1.19.5'

2. Create a null vector of size 10

In [2]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create Simple 1-D array and check type and check data types in array

In [3]:
a = np.array([1.2,2.3,4.3,5.4,5.6])
print(a)
print(type(a))
print(a.dtype)

[1.2 2.3 4.3 5.4 5.6]
<class 'numpy.ndarray'>
float64


4. How to find number of dimensions, bytes per element and bytes of memory used?

In [4]:
import sys
a = np.array([[1.2,2.3,4.3,5.4,5.6],[1.2,2.3,4.3,5.4,5.6]])
print(a.ndim)
print(a.itemsize)
print(a.size)
print(a.size*a.itemsize)

2
8
10
80


5. Create a null vector of size 10 but the fifth value which is 1

In [5]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

6. Create a vector with values ranging from 10 to 49

In [7]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

7. Reverse a vector (first element becomes last)

In [8]:
a=np.arange(10,50)
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


8. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
a=np.arange(9)
print(a.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


9. Find indices of non-zero elements from [1,2,0,0,4,0]

In [10]:
a=np.array([1,2,0,0,4,0])
np.where(a!=0)

(array([0, 1, 4]),)

10. Create a 3x3 identity matrix

In [11]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11. Create a 3x3x3 array with random values

In [12]:
import random

a=np.random.random((3,3,3))
a

array([[[0.54858118, 0.49710727, 0.72224738],
        [0.4138759 , 0.79581185, 0.53716204],
        [0.91630218, 0.86636628, 0.2519889 ]],

       [[0.29219099, 0.97628116, 0.04110224],
        [0.87077053, 0.71957693, 0.73090141],
        [0.84489925, 0.69673369, 0.36343071]],

       [[0.96276685, 0.20449496, 0.95973628],
        [0.32251369, 0.32530395, 0.11024314],
        [0.09707576, 0.90800502, 0.45039624]]])

12. Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
import random
a=np.random.random((10,10))
print(a,"\n\n")
print(a.max(),a.min())

[[0.69110153 0.84820986 0.84916882 0.44698564 0.92200757 0.2315953
  0.72653178 0.55074766 0.5907599  0.26335825]
 [0.56565986 0.04823271 0.04685146 0.49318802 0.00184218 0.19567751
  0.9526842  0.52565334 0.01572608 0.56508913]
 [0.05176745 0.24031126 0.61518428 0.5869711  0.04017833 0.59394192
  0.79933882 0.26913794 0.2439409  0.69417194]
 [0.93282929 0.96216712 0.07595735 0.83891925 0.29739039 0.95674402
  0.86220255 0.67937347 0.23162551 0.03797867]
 [0.84413251 0.13172863 0.9613381  0.87787582 0.70257026 0.32033603
  0.97653719 0.44913716 0.44688624 0.84903918]
 [0.05457486 0.87995159 0.29537185 0.36009847 0.64764031 0.92413002
  0.31273918 0.47707087 0.73160882 0.06809845]
 [0.01158207 0.92815709 0.95452431 0.53336953 0.74212134 0.72392294
  0.99041011 0.43318612 0.383238   0.92623901]
 [0.70527947 0.82732865 0.25080372 0.46262034 0.76658824 0.49552197
  0.69108937 0.01927025 0.56991977 0.41865143]
 [0.02011541 0.85863769 0.30837778 0.61960799 0.8622568  0.07380609
  0.38213939 

13. Create a random vector of size 30 and find the mean value

In [14]:
import random
a=np.random.random(30)
print(a)
a.mean()

[0.7803995  0.84315898 0.79159783 0.95863841 0.53583491 0.86801631
 0.42399192 0.58781975 0.7677723  0.34088351 0.79374336 0.33604107
 0.95885401 0.51484041 0.43374917 0.54717464 0.77034438 0.39051986
 0.8796857  0.45122213 0.33938275 0.05689104 0.21871479 0.65899972
 0.90407304 0.40674305 0.0361648  0.97908033 0.84109734 0.11568635]


0.5843707121031391

14 . Create a 2d array with 1 on the border and 0 inside

In [18]:
a=np.zeros((5,6))
m,n=a.shape
for i in range(m):
  for j in range(n):
    a[i][0]=1
    a[0][j]=1
    a[m-1][j]=1
    a[i][n-1]=1
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


15. How to add a border (filled with 0's) around an existing array? 

In [21]:
import numpy as np
a = np.ones((3,3))
print(a,"\n\n")
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# 16. How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?    
Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]  

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [22]:
a=[[ 1,2,3,4,5,6, 7],[ 8 ,9 ,10 ,11 ,12 ,13 ,14]]
a[1][5]=20
a

[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 20, 14]]

17. How to Convert a 1D array to a 2D array with 2 rows

In [23]:
a=np.ones(10)
a.reshape(2,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Create the following pattern without hardcoding. Use only numpy functions and the below input array a.  
Input:

a = np.array([1,2,3])`

Desired Output:

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [24]:
a = np.array([1,2,3])
a=np.append(np.repeat(a,3),np.tile(a,3))
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

19.Write a program to show how Numpy taking less memory compared to Python List?

In [25]:
import sys
l=[i for i in range(1000)]
print("for list:",sys.getsizeof(10)*len(l))
arr=np.arange(1000)
print("for nparray:",arr.itemsize*len(arr))
arr[0]

for list: 28000
for nparray: 8000


0

20. Write a program to show how Numpy taking less time compared to Python List?

In [26]:
import time
import sys

l1=[i for i in range(1000)]
l2=[i for i in range(1000)]
start=time.time()
l1+l2
print("for list:",(time.time()-start)*1000)
arr1=np.arange(1000)
arr2=np.arange(1000)
start=time.time()
arr1+arr2
print("for nparray:",(time.time()-start)*1000)

for list: 0.051021575927734375
for nparray: 0.1010894775390625
